version: "3.8"

services:

  # php:
  #   image: php:latest

  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:latest
    volumes:
      - ./node:/var/bin/www
    ports:
      - 3000:3000
