name: test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: test env vars
        env:
          TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}
        run: |
          echo "$TEST_ENV_VARS"
          echo "$TEST_ENV_VARS" >> .env
      - uses: actions/upload-artifact@v3
        with:
          name: env-var
          path: .env
